services:
  - type: web
    name: time-machine-app
    env: python
    region: frankfurt  # Или singapore, ohio, etc
    plan: free
    branch: main
    
    buildCommand: | 
      pip install -r requirements.txt
      
    startCommand: |
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
      
    envVars:
      - key: YANDEX_API_KEY
        sync: false
      - key: YANDEX_FOLDER_ID
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"